### ISSUE TITLE
Results No messages can be imported for label: Notes

### ISSUE THREAD

**Issue by utkarshmttl** [lambrospetrou/gmail-keep-importer#11]
It doesn't connect with Gmail account at all, and finds no messages with any labels.

**Comment by dgitman** [comment]
I'm also not being promoted to authorize access to emails on first use.

**Comment by lambrospetrou** [comment]
This is the same issue as #10 so it seems that Google changed how their Gmail API works with the JS client, and once you trigger the authentication it does not execute the callback function you provide. 

Actually I noticed the same problem on another website I was using Google as SSO.

I will try and fix the issue this week since many people are being blocked from using the extension.

Thanks for reporting it. Please follow the progress on this in the initial issue that reported this.

**Comment by dgitman** [comment]
@lambrospetrou thanks for the nice update and keeping this project alive.
