### ISSUE TITLE
Error while importing TypeError: Cannot read property 'click' of null error

### ISSUE THREAD

**Issue by gabrieljoelc** [lambrospetrou/gmail-keep-importer#2]
I received this error multiple times:

![image](https://cloud.githubusercontent.com/assets/147849/21158061/0438f3d8-c139-11e6-9db1-cba958699f94.png)

I removed and reinstalled and got this error:

![image](https://cloud.githubusercontent.com/assets/147849/21158159/5048393c-c139-11e6-9059-1c7c65e4a97b.png)

**Comment by lambrospetrou** [comment]
Hi, the problem is probably because Google updated the website and some elements now are coded with different IDs or a you are not in the required page.

In order for the plugin to work you had to be in this page: https://keep.google.com/#home
which shows your notes in a card layout, with the new note text box and the DONE button at the top.

Please go to that page and try again, I have reports that the plugin still works if you are on that page.
