### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by atxer** [lambrospetrou/gmail-keep-importer#4]
Hello!
I am using Windows10 and Chrome. 
I followed all the instructions and everything went fine: authorized, found emails and when clicking "Start import" it just says "undefined".
What can be the issue?
Thanks in advance!

**Comment by amyspivey** [comment]
I also having this problem with Chrome and Mac OS X El Capitan.

**Comment by atxer** [comment]
It worked just now!! 💃

**Comment by lambrospetrou** [comment]
Hello,

Well the weird thing is that it worked;p

As I said in another issue opened, Google updated the Keep website few months ago so the extension stopped working because the homepage structure changed. 

If it worked for you now it means that you were in the **Notes** section of the page and not the new homepage. 

The fact that it still works if you are in the notes section is good;p
Glad you got it working.
